projectTitle = "WayGL"
modId = "waygl"
githubRepo = "wired-tomato/WayGL"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "wiredtomato" ]
majorMinecraftVersion = "1.17"
minecraftVersion = "1.17"
fabricLoaderVersion = "0.14.21"
fabricApiVersion = "0.36.0+1.17"
fabricLangKotlinVersion = "1.10.16+kotlin.1.9.21"
license = "MIT"
modules = [ ]

[mappings]
    # You have 6 mapping types
    # MOJANG: The official Mojang mappings
    # YARN: Yarn mappings
    # PARCHMENT: Parchment mappings
    # QUILT: Quilt mappings
    # MOJPARCH: Parchment layered on top of the official Mojang mappings
    # MOJYARN: Yarn layered on top of the official Mojang mappings
    type = "YARN"
    version = "1.17+build.13"